### ISSUE TITLE
HUD does not appear.

### ISSUE THREAD

**Issue by theMagius0** [mrcomac/enhancedcombathud-swade#22]
**Foundry**: 12.331
**SWADE**: 4.1.1
**Argon (CORE):** 3.1.0 
**Argon (SWADE):** 1.0.3

I am unable to see the Argon HUD (at all) when clicking on a character icon, and selecting the "Toggle Argon Combat HUD" option.  I see the macro bar disappear just fine at the bottom of the screen.  But no HUD.

I have created a clean environment with only the following modules:
- Argon(Core)
- Argon(SWADE)
- lib-ColorSettings
- Savage Worlds Adventure Edition Core Rules
- The Forge

Is there something I'm doing wrong?

Thx,

**Comment by mrcomac** [comment]
it is due to latest argon hud core update.
new release fix it.

**Comment by jasharen** [comment]
Issue is still appearing for me
SWADE 4.2.0
Argon (CORE): 3.1.0
Argon (SWADE): 1.0.4

Error on attempting to open:
foundry.js:655 Error: An error occurred while rendering CoreHUD 38. Cannot read properties of undefined (reading 'value')
[Detected 2 packages: enhancedcombathud-swade(1.0.4), enhancedcombathud(3.1.0)]
    at Hooks.onError (foundry.js:654:24)
    at 🎁Hooks.onError#0 (libWrapper-wrapper.js:188:54)
    at foundry.js:5795:13
Caused by: TypeError: Cannot read properties of undefined (reading 'value')
[Detected 2 packages: enhancedcombathud-swade(1.0.4), enhancedcombathud(3.1.0)]
    at get movementMax (argo-swade.min.js:1:23211)
    at get movementColor (movementHud.js:26:74)
    at SWADEMovementHud.updateMovement (movementHud.js:50:32)
    at SWADEMovementHud.render (movementHud.js:82:10)
    at async Promise.all (index 1)
    at async CoreHUD._renderInner (hud.js:282:9)
    at async CoreHUD._render (foundry.js:5844:19)
