### ISSUE TITLE
Hud does not appear

### ISSUE THREAD

**Issue by jasharen** [mrcomac/enhancedcombathud-swade#23]
Issue of HUD not appearing is still an issue for me
SWADE 4.2.0
Argon (CORE): 3.1.0
Argon (SWADE): 1.0.4

Error on attempting to open:
foundry.js:655 Error: An error occurred while rendering CoreHUD 38. Cannot read properties of undefined (reading 'value')
[Detected 2 packages: enhancedcombathud-swade(1.0.4), enhancedcombathud(3.1.0)]
at Hooks.onError (foundry.js:654:24)
at 🎁Hooks.onError#0 (libWrapper-wrapper.js:188:54)
at foundry.js:5795:13
Caused by: TypeError: Cannot read properties of undefined (reading 'value')
[Detected 2 packages: enhancedcombathud-swade(1.0.4), enhancedcombathud(3.1.0)]
at get movementMax (argo-swade.min.js:1:23211)
at get movementColor (movementHud.js:26:74)
at SWADEMovementHud.updateMovement (movementHud.js:50:32)
at SWADEMovementHud.render (movementHud.js:82:10)
at async Promise.all (index 1)
at async CoreHUD._renderInner (hud.js:282:9)
at async CoreHUD._render (foundry.js:5844:19)

**Comment by jasharen** [comment]
Dug into the problem. It appears that get movementMax fails based on an actor not having a defined speed. Quick hack fix:
            get movementMax() {
                //Check to see if this.actor.system.stats.speed.value is undefined and catch it without letting an error occur
                if (this.actor.system.stats?.speed?.value == undefined) {
                    return 0
                } else {
                    return 0 != o ? o / canvas.scene.dimensions.distance : this.actor.system.stats
                        ?.speed?.value / canvas.scene.dimensions.distance
                }
            }

**Comment by flyingsquad** [comment]
I cloned the repository and made the changes suggested above and got the HUD to appear.

However, some things don't work. When I click Powers for characters that have them nothing happens. I assume that the powers should pop up like the spells do in the D&D version of the HUD. The console displays the following error when I select a token that has powers:

Uncaught (in promise) TypeError: this.system.range.match is not a function
[Detected 3 packages: system:swade(4.2.0), enhancedcombathud-swade(1.0.4), enhancedcombathud(3.1.0)]
    at get range (SwadeItem.ts:115:37)
    at get quantity (config.js:723:29)
    at SWADEItemButton.getData (itemButton.js:76:27)
    at SWADEItemButton._renderInner (component.js:136:33)
    at SWADEItemButton._renderInner (itemButton.js:148:17)
    at SWADEItemButton.render (component.js:126:20)
    at SWADEItemButton.render (config.js:704:29)
    at buttonPanel.js:63:63
    at Array.map (<anonymous>)
    at ButtonPanel._renderInner (buttonPanel.js:63:40)
    at async ButtonPanel.render (component.js:126:9)
    at async SWADEButtonPanelButton._renderInner (buttonPanelButton.js:55:5)
    at async SWADEButtonPanelButton.render (component.js:126:9)

**Comment by mrcomac** [comment]
The SWADE system has had some recent changes that might be the reason for that. I'll be back in front of my computer in the third week of January to look into this issue. I'm assuming the Token Action HUD for SWADE is having similar issues that will need some code review and fix as well. it seems a fix for 2 modules.

**Comment by flyingsquad** [comment]
Yes, you're right. I usually use Token Action HUD and it completely ignores the SWADE Tools versions of the actions. Argon uses the SWADE Tools actions, but the Powers aren't popping up when I click the Powers button.

And thanks for looking at this!

**Comment by mrcomac** [comment]
Hi @flyingsquad and @jasharen 
Hope the new version fixes the issues, if not, please share your characters json.

**Comment by flyingsquad** [comment]
All the things I tried work. Thanks!
